name: Deploy LambdaStack


permissions:
 id-token: write # Required for GitHub to be able to create a token for you to authenticate with AWS
 contents: read  # Permits your action to read this repo.


on:
 push:
   branches:
     - main


jobs:
 deploy_django_stack:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout this repo
       uses: actions/checkout@v4

     - name: Setup Node.js
       uses: actions/setup-node@v4
       with:
           node-version: 20

     - name: Install dependencies
       run: npm install

     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
         role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_ROLE }}
         aws-region: ${{ vars.AWS_TARGET_REGION }}
         role-session-name: "GitHubActions-DeployLayerStack"

     - name: Deploy DjangoStack (via CDK)
       run: yarn cdk deploy DjangoStack --require-approval never